### ISSUE TITLE
Finding out which rules lead to each chunk in parse

### ISSUE THREAD

**Issue by keorn** [wdebeaum/PEG.jl#6]
I have a set of rules and after parsing I would like to easily determine which ones were applied during parsing. Is there a way to find that out?

**Comment by wdebeaum** [comment]
There are a couple of ways you could do this:

 1. Calling `PEG.setdebug!()` will turn on debugging, which prints each rule (or part of a rule) that matches, as it matches, along with the indexes where it matched (relative to the end of the input), and the value it returned. This information is indented according to the current stack depth.

 2. You could add your own julia code to each rule (with the semantics operators `|>` or `>`), that logs the information you want, where you want it. You could write it to a stream, put it in some global data structure, or include it in what you return from the rule.

I'd recommend (1) if you just want to debug your parser, and (2) if you want to use this information in other parts of your program (e.g. for syntax highlighting, or providing other feedback about how you parsed something the user sent you).

**Comment by keorn** [comment]
I was also looking at the cache, but now I see `|>`, `>` are what I was looking for. I was not clear from the README what they do. Very neat!
